version: "3.7"

services:
  frontend:
    build: frontend
    ports:
      - 8504:8501
    networks:
      AIservice:
        aliases:
          - frontend.docker
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - ./data:/data

  backend:
    build: backend
    ports:
      - 8000:8000
    networks:
      AIservice:
        aliases:
          - backend.docker
    volumes:
      - ./backend:/app
      - ./data:/data

networks:
  AIservice:
    external: true
